Check if command rails is available in the rails service.

diff --git a/dependencies/templates/default/rails.erb b/dependencies/templates/default/rails.erb
--- a/dependencies/templates/default/rails.erb
+++ b/dependencies/templates/default/rails.erb
@@ -1,58 +1,63 @@
 #!/bin/bash
 
 start() {
-        echo "Starting rails"
-		if [ -e /vagrant/config/database.yml ]
-		then
-			ENV=${RAILS_ENV:-development}
-			if [ -e /vagrant/tmp/pids/server.pid ]
-			then 
-				echo "Rails already running"
-			else 
-				sudo su - vagrant -c "cd /vagrant && rails server -d -e $ENV"
-			fi
-			
-			if [ -e /vagrant/tmp/pids/thin.pid ]
-			then
-				echo "Thin already running"
-			else
-				sudo su - vagrant -c "cd /vagrant && rackup private_pub.ru -D -P tmp/pids/thin.pid -s thin -E $ENV -p 9290"
-			fi
-		else 
-			echo "/vagrant/config/database.yml is missing. Aborting";
-			echo "To fix, run cp /vagrant/config/database.example.yml /vagrant/config/database.yml";
-		fi
+
+  if ! which rails &> /dev/null
+  then
+    echo "Cannot find command rails. Did you forget to run 'bundle install'?"
+    exit 0
+  fi
+
+  if [ -e /vagrant/config/database.yml ]
+  then
+    ENV=${RAILS_ENV:-development}
+    if [ -e /vagrant/tmp/pids/server.pid ]
+    then 
+      echo "Rails already running"
+    else
+      echo "Starting rails"
+      sudo su - vagrant -c "cd /vagrant && rails server -d -e $ENV"
+    fi
+
+    if [ -e /vagrant/tmp/pids/thin.pid ]
+    then
+      echo "Thin already running"
+    else
+      sudo su - vagrant -c "cd /vagrant && rackup private_pub.ru -D -P tmp/pids/thin.pid -s thin -E $ENV -p 9290"
+    fi
+  else 
+    echo "Cannot find /vagrant/config/database.yml. Did you forget to run 'cp /vagrant/config/database.yml.example /vagrant/config/database.yml'?";
+  fi
 }
 
 stop() {
-        echo "Stopping rails"
-        if [ -e /vagrant/tmp/pids/server.pid ]
-		then 
-			sudo su - vagrant -c "cd /vagrant && sudo kill `cat /vagrant/tmp/pids/server.pid`"
-		fi
-		
-		if [ -e /vagrant/tmp/pids/thin.pid ]
-		then
-			sudo su - vagrant -c "cd /vagrant && sudo kill `cat /vagrant/tmp/pids/thin.pid`"
-		fi
+  echo "Stopping rails"
+  if [ -e /vagrant/tmp/pids/server.pid ]
+  then 
+    sudo su - vagrant -c "cd /vagrant && sudo kill `cat /vagrant/tmp/pids/server.pid`"
+  fi
+
+  if [ -e /vagrant/tmp/pids/thin.pid ]
+  then
+    sudo su - vagrant -c "cd /vagrant && sudo kill `cat /vagrant/tmp/pids/thin.pid`"
+  fi
 }
 
 restart() {
-        stop
-        start
+  stop
+  start
 }
 
 case "$1" in
 start)
-        start
+  start
 ;;
 stop)
-        stop
+  stop
 ;;
 restart)
-        restart
+  restart
 ;;
 *) echo $"Usage: $0 {start|stop|restart}"
 ;;
 esac
-
